#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import textwrap
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


DISPOSITION_KEEP = "keep"
DISPOSITION_DROP = "drop"
DISPOSITION_UNCERTAIN = "uncertain"


CWE_HINTS = {
    "sql-injection": "Only strong evidence such as parameterized queries / prepared statements should count as effective mitigation. Simple regex replacement or blacklist filtering usually does not fully stop SQL injection.",
    "ssrf": "Only strong evidence such as strict scheme+host/IP allowlists after parsing should count as effective mitigation. startsWith checks and substring checks are weak.",
    "command-injection": "Only strong evidence such as a fixed allowlist, enum dispatch, or fully fixed command template should count as effective mitigation. Shell concatenation is still dangerous.",
    "path-traversal": "Normalization alone is not enough. Effective mitigation usually requires canonical/normalized path checking plus containment under a trusted base directory, or a strict filename allowlist.",
    "xss": "The encoding must match the output context. Generic HTML escaping may not be enough for JavaScript, URL, CSS, or attribute contexts.",
    "log-injection": "Effective mitigation usually means neutralizing CR/LF or using structured logging where tainted data is not interpreted as part of the log format.",
    "unsafe-deserialization": "Unsafe deserialization is only clearly mitigated when the input is not user-controlled, or when deserialization is replaced with a safe format / strict type restriction.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Filter CodeQL SARIF path alerts with an OpenAI-compatible LLM."
    )
    parser.add_argument("--sarif", required=True, help="Input SARIF generated by CodeQL")
    parser.add_argument("--repo-root", required=True, help="Repository root used to load source snippets")
    parser.add_argument("--out-sarif", required=True, help="Filtered output SARIF path")
    parser.add_argument("--out-jsonl", required=True, help="Per-alert LLM decisions as JSONL")
    parser.add_argument("--model", default="gpt-4o-mini", help="Model name")
    parser.add_argument(
        "--base-url",
        default="https://api.openai.com/v1",
        help="OpenAI-compatible base URL, for example https://api.openai.com/v1 or http://localhost:11434/v1",
    )
    parser.add_argument(
        "--api-key-env",
        default="OPENAI_API_KEY",
        help="Environment variable containing the API key",
    )
    parser.add_argument(
        "--drop-confidence",
        type=float,
        default=0.85,
        help="Only drop alerts when disposition=drop and confidence >= this value",
    )
    parser.add_argument(
        "--max-steps",
        type=int,
        default=8,
        help="Maximum number of path steps to send to the LLM",
    )
    parser.add_argument(
        "--context-lines",
        type=int,
        default=12,
        help="Number of surrounding source lines to include around each step",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=180,
        help="HTTP timeout per LLM request",
    )
    parser.add_argument(
        "--max-reason-chars",
        type=int,
        default=1500,
        help="Truncate detailed_reason to this many characters in SARIF annotations",
    )
    return parser.parse_args()


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_jsonl(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def normalize_uri(uri: str) -> str:
    if not uri:
        return ""
    uri = uri.replace("\\", "/")
    if uri.startswith("file://"):
        uri = uri[7:]
    return uri


def resolve_source_path(repo_root: Path, uri: str) -> Optional[Path]:
    uri = normalize_uri(uri)
    if not uri:
        return None

    p = Path(uri)
    if p.is_absolute():
        return p if p.exists() else None

    candidate = (repo_root / uri).resolve()
    try:
        candidate.relative_to(repo_root.resolve())
    except ValueError:
        return None
    return candidate if candidate.exists() else None


def get_region_start(location: Dict[str, Any]) -> Tuple[int, int]:
    try:
        region = location["physicalLocation"]["region"]
        return int(region.get("startLine", 1)), int(region.get("startColumn", 1))
    except Exception:
        return 1, 1


def get_region_end(location: Dict[str, Any]) -> Tuple[int, int]:
    try:
        region = location["physicalLocation"]["region"]
        return int(region.get("endLine", region.get("startLine", 1))), int(region.get("endColumn", 1))
    except Exception:
        return 1, 1


def get_uri(location: Dict[str, Any]) -> str:
    try:
        return normalize_uri(location["physicalLocation"]["artifactLocation"]["uri"])
    except Exception:
        return ""


def read_snippet(repo_root: Path, location: Dict[str, Any], context_lines: int) -> Dict[str, Any]:
    uri = get_uri(location)
    start_line, start_col = get_region_start(location)
    end_line, end_col = get_region_end(location)
    path = resolve_source_path(repo_root, uri)

    snippet: Dict[str, Any] = {
        "uri": uri,
        "startLine": start_line,
        "startColumn": start_col,
        "endLine": end_line,
        "endColumn": end_col,
        "path": str(path) if path else None,
        "code": "[source unavailable]",
    }

    if path is None:
        return snippet

    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return snippet

    lines = text.splitlines()
    lo = max(1, start_line - context_lines)
    hi = min(len(lines), end_line + context_lines)
    numbered = []
    for i in range(lo, hi + 1):
        prefix = ">" if start_line <= i <= end_line else " "
        numbered.append(f"{prefix}{i:5d}: {lines[i - 1]}")
    snippet["code"] = "\n".join(numbered)
    return snippet


def dedupe_locations(locations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    out = []
    for loc in locations:
        key = (get_uri(loc),) + get_region_start(loc) + get_region_end(loc)
        if key in seen:
            continue
        seen.add(key)
        out.append(loc)
    return out


def extract_path_locations(result: Dict[str, Any]) -> List[Dict[str, Any]]:
    code_flows = result.get("codeFlows") or []
    collected: List[Dict[str, Any]] = []
    for code_flow in code_flows:
        for thread_flow in code_flow.get("threadFlows", []) or []:
            for step in thread_flow.get("locations", []) or []:
                loc = step.get("location")
                if isinstance(loc, dict):
                    collected.append(loc)

    if not collected:
        for loc in result.get("locations", []) or []:
            if isinstance(loc, dict):
                collected.append(loc)

    return dedupe_locations(collected)


def select_key_steps(locations: List[Dict[str, Any]], max_steps: int) -> List[Dict[str, Any]]:
    if len(locations) <= max_steps:
        return locations
    if max_steps < 2:
        return [locations[0]]

    picked_indices = {0, len(locations) - 1}
    interior_slots = max_steps - 2
    for slot in range(interior_slots):
        frac = (slot + 1) / (interior_slots + 1)
        idx = int(round(frac * (len(locations) - 1)))
        picked_indices.add(min(len(locations) - 1, max(0, idx)))

    ordered = [locations[i] for i in sorted(picked_indices)]
    return ordered[:max_steps]


def first_primary_location(result: Dict[str, Any]) -> Dict[str, Any]:
    locations = result.get("locations") or []
    if locations and isinstance(locations[0], dict):
        return locations[0]
    path_locations = extract_path_locations(result)
    return path_locations[0] if path_locations else {}


def build_rule_map(run: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}

    def add_rules(rules: List[Dict[str, Any]]) -> None:
        for rule in rules or []:
            if not isinstance(rule, dict):
                continue
            rid = rule.get("id")
            if not rid:
                continue
            out[rid] = rule

    tool = run.get("tool", {}) or {}
    driver = tool.get("driver", {}) or {}
    add_rules(driver.get("rules", []) or [])
    for ext in tool.get("extensions", []) or []:
        add_rules(ext.get("rules", []) or [])
    return out


def get_rule_description(rule: Dict[str, Any]) -> str:
    for key in ("fullDescription", "shortDescription"):
        val = rule.get(key)
        if isinstance(val, dict) and val.get("text"):
            return str(val["text"])
    return ""


def infer_hint(rule_id: str, message: str) -> str:
    keyspace = f"{rule_id} {message}".lower()
    for key, hint in CWE_HINTS.items():
        if key in keyspace:
            return hint
    return "Drop an alert only if the provided code clearly proves that attacker-controlled data is rendered safe for this exact sink and vulnerability type."


def build_alert_payload(
    repo_root: Path,
    rule_map: Dict[str, Dict[str, Any]],
    result: Dict[str, Any],
    max_steps: int,
    context_lines: int,
) -> Dict[str, Any]:
    rule_id = result.get("ruleId", "")
    rule = rule_map.get(rule_id, {})
    rule_desc = get_rule_description(rule)
    message = (result.get("message") or {}).get("text", "")
    primary = first_primary_location(result)
    primary_uri = get_uri(primary)
    primary_line, primary_col = get_region_start(primary)

    all_locations = extract_path_locations(result)
    key_locations = select_key_steps(all_locations, max_steps)

    snippets: List[Dict[str, Any]] = []
    for idx, loc in enumerate(key_locations):
        snippet = read_snippet(repo_root, loc, context_lines)
        snippet["stepIndex"] = idx
        if idx == 0:
            snippet["role"] = "source-ish"
        elif idx == len(key_locations) - 1:
            snippet["role"] = "sink-ish"
        else:
            snippet["role"] = "intermediate"
        snippets.append(snippet)

    return {
        "ruleId": rule_id,
        "ruleDescription": rule_desc,
        "message": message,
        "primaryLocation": {
            "uri": primary_uri,
            "startLine": primary_line,
            "startColumn": primary_col,
        },
        "pathStepCount": len(all_locations),
        "selectedSteps": snippets,
        "hint": infer_hint(rule_id, message),
    }


def build_prompt(payload: Dict[str, Any]) -> Tuple[str, str]:
    system_prompt = textwrap.dedent(
        """
        You are a senior Java application security reviewer.
        You are reviewing one CodeQL candidate data-flow/path alert.
        Be conservative: keep the alert unless the evidence clearly shows that this exact vulnerability is neutralized for this exact sink context.
        Do not assume unseen code is safe.
        Return strict JSON only.
        """
    ).strip()

    user_prompt = {
        "task": (
            "Decide whether this CodeQL candidate alert should be kept, dropped as a likely false positive, "
            "or marked uncertain. Focus on whether validations, sanitizers, allowlists, parameterization, "
            "normalization, or encoding on the shown path actually neutralize the risk at the sink."
        ),
        "decision_policy": {
            "keep": "Likely exploitable, or evidence is insufficient to prove safety.",
            "drop": "The shown evidence clearly proves effective mitigation for this CWE and sink context.",
            "uncertain": "The shown evidence is mixed or incomplete.",
        },
        "required_output": {
            "disposition": "keep | drop | uncertain",
            "confidence": "number between 0 and 1",
            "sanitizer_effective": "true | false | null",
            "short_reason": "short string, <= 300 chars",
            "detailed_reason": "string, concise but specific",
        },
        "alert": payload,
    }
    return system_prompt, json.dumps(user_prompt, ensure_ascii=False, indent=2)


def openai_chat_completion(
    base_url: str,
    api_key: str,
    model: str,
    system_prompt: str,
    user_prompt: str,
    timeout_seconds: int,
) -> str:
    if not api_key:
        raise RuntimeError("Missing API key")

    base_url = base_url.rstrip("/")
    if not base_url.endswith("/chat/completions"):
        url = base_url + "/chat/completions"
    else:
        url = base_url

    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0,
        "response_format": {"type": "json_object"},
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )

    with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return payload["choices"][0]["message"]["content"]


def normalize_llm_decision(raw: Dict[str, Any], fallback_reason: str = "") -> Dict[str, Any]:
    disposition = str(raw.get("disposition", DISPOSITION_UNCERTAIN)).strip().lower()
    if disposition not in {DISPOSITION_KEEP, DISPOSITION_DROP, DISPOSITION_UNCERTAIN}:
        disposition = DISPOSITION_UNCERTAIN

    try:
        confidence = float(raw.get("confidence", 0.5))
    except (TypeError, ValueError):
        confidence = 0.5
    confidence = max(0.0, min(1.0, confidence))

    sanitizer_effective = raw.get("sanitizer_effective")
    if sanitizer_effective not in (True, False, None):
        sanitizer_effective = None

    short_reason = str(raw.get("short_reason", "")).strip()
    detailed_reason = str(raw.get("detailed_reason", "")).strip()
    if not short_reason:
        short_reason = fallback_reason or "No short reason returned by model."
    if not detailed_reason:
        detailed_reason = short_reason

    return {
        "disposition": disposition,
        "confidence": confidence,
        "sanitizer_effective": sanitizer_effective,
        "short_reason": short_reason,
        "detailed_reason": detailed_reason,
    }


def fallback_decision(error_text: str) -> Dict[str, Any]:
    return {
        "disposition": DISPOSITION_UNCERTAIN,
        "confidence": 0.0,
        "sanitizer_effective": None,
        "short_reason": f"LLM call failed: {error_text}",
        "detailed_reason": f"LLM call failed, so the alert was kept for manual review. Error: {error_text}",
    }


def run_llm(args: argparse.Namespace, payload: Dict[str, Any]) -> Dict[str, Any]:
    api_key = os.getenv(args.api_key_env, "")
    if not api_key:
        return fallback_decision(
            f"environment variable {args.api_key_env} is not set"
        )

    system_prompt, user_prompt = build_prompt(payload)
    try:
        raw_text = openai_chat_completion(
            base_url=args.base_url,
            api_key=api_key,
            model=args.model,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            timeout_seconds=args.timeout_seconds,
        )
        parsed = json.loads(raw_text)
        return normalize_llm_decision(parsed)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        return fallback_decision(f"HTTP {exc.code}: {detail}")
    except Exception as exc:  # noqa: BLE001
        return fallback_decision(str(exc))


def annotate_result(result: Dict[str, Any], decision: Dict[str, Any], max_reason_chars: int) -> None:
    props = result.setdefault("properties", {})
    props["llm_triage"] = {
        "disposition": decision["disposition"],
        "confidence": decision["confidence"],
        "sanitizer_effective": decision["sanitizer_effective"],
        "short_reason": decision["short_reason"],
        "detailed_reason": decision["detailed_reason"][:max_reason_chars],
    }


def should_drop(decision: Dict[str, Any], threshold: float) -> bool:
    return (
        decision.get("disposition") == DISPOSITION_DROP
        and float(decision.get("confidence", 0.0)) >= threshold
    )


def process_sarif(args: argparse.Namespace) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    sarif_path = Path(args.sarif)
    out_sarif_path = Path(args.out_sarif)
    out_jsonl_path = Path(args.out_jsonl)
    repo_root = Path(args.repo_root).resolve()

    data = load_json(sarif_path)
    decision_rows: List[Dict[str, Any]] = []

    total_before = 0
    total_after = 0
    total_dropped = 0

    for run_index, run in enumerate(data.get("runs", [])):
        rule_map = build_rule_map(run)
        new_results: List[Dict[str, Any]] = []
        results = run.get("results", []) or []
        total_before += len(results)

        for result_index, result in enumerate(results):
            payload = build_alert_payload(
                repo_root=repo_root,
                rule_map=rule_map,
                result=result,
                max_steps=args.max_steps,
                context_lines=args.context_lines,
            )
            decision = run_llm(args, payload)
            annotate_result(result, decision, args.max_reason_chars)

            primary = payload["primaryLocation"]
            row = {
                "runIndex": run_index,
                "resultIndex": result_index,
                "ruleId": payload["ruleId"],
                "message": payload["message"],
                "primaryLocation": primary,
                "pathStepCount": payload["pathStepCount"],
                "decision": decision,
            }
            decision_rows.append(row)

            if should_drop(decision, args.drop_confidence):
                total_dropped += 1
                continue
            new_results.append(result)

        run["results"] = new_results
        total_after += len(new_results)
        run.setdefault("properties", {})["llm_filter_summary"] = {
            "results_before": len(results),
            "results_after": len(new_results),
            "results_dropped": len(results) - len(new_results),
            "drop_confidence": args.drop_confidence,
            "model": args.model,
            "base_url": args.base_url,
        }

    save_json(out_sarif_path, data)
    write_jsonl(out_jsonl_path, decision_rows)

    print(f"[OK] Input SARIF   : {sarif_path}")
    print(f"[OK] Output SARIF  : {out_sarif_path}")
    print(f"[OK] Decisions JSONL: {out_jsonl_path}")
    print(f"[OK] Results before: {total_before}")
    print(f"[OK] Results dropped: {total_dropped}")
    print(f"[OK] Results after : {total_after}")

    return data, decision_rows


def main() -> int:
    args = parse_args()
    process_sarif(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
